import { OPERATIONS_TABLE_COLUMN_NAMES } from '@widgets/operations-table/model/constants.ts';

export interface OperationsTableValues {
  [OPERATIONS_TABLE_COLUMN_NAMES.ID]: number;
  [OPERATIONS_TABLE_COLUMN_NAMES.STARTED]: string;
  [OPERATIONS_TABLE_COLUMN_NAMES.FINISHED]: string;
  [OPERATIONS_TABLE_COLUMN_NAMES.TYPE]: string;
  [OPERATIONS_TABLE_COLUMN_NAMES.STATUS]: string;
  [OPERATIONS_TABLE_COLUMN_NAMES.CLUSTER]: string;
  [OPERATIONS_TABLE_COLUMN_NAMES.ENVIRONMENT]: string;
}
