// Code generated by go-swagger; DO NOT EDIT.

package dictionary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetExternalDeploymentsHandlerFunc turns a function with the right signature into a get external deployments handler
type GetExternalDeploymentsHandlerFunc func(GetExternalDeploymentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetExternalDeploymentsHandlerFunc) Handle(params GetExternalDeploymentsParams) middleware.Responder {
	return fn(params)
}

// GetExternalDeploymentsHandler interface for that can handle valid get external deployments params
type GetExternalDeploymentsHandler interface {
	Handle(GetExternalDeploymentsParams) middleware.Responder
}

// NewGetExternalDeployments creates a new http.Handler for the get external deployments operation
func NewGetExternalDeployments(ctx *middleware.Context, handler GetExternalDeploymentsHandler) *GetExternalDeployments {
	return &GetExternalDeployments{Context: ctx, Handler: handler}
}

/*
	GetExternalDeployments swagger:route GET /external/deployments dictionary getExternalDeployments

Get full info about available external deployments
*/
type GetExternalDeployments struct {
	Context *middleware.Context
	Handler GetExternalDeploymentsHandler
}

func (o *GetExternalDeployments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetExternalDeploymentsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
