// Code generated by go-swagger; DO NOT EDIT.

package dictionary

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"postgesql-cluster-console/models"
)

// GetExternalDeploymentsOKCode is the HTTP code returned for type GetExternalDeploymentsOK
const GetExternalDeploymentsOKCode int = 200

/*
GetExternalDeploymentsOK OK

swagger:response getExternalDeploymentsOK
*/
type GetExternalDeploymentsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseDeploymentsInfo `json:"body,omitempty"`
}

// NewGetExternalDeploymentsOK creates GetExternalDeploymentsOK with default headers values
func NewGetExternalDeploymentsOK() *GetExternalDeploymentsOK {

	return &GetExternalDeploymentsOK{}
}

// WithPayload adds the payload to the get external deployments o k response
func (o *GetExternalDeploymentsOK) WithPayload(payload *models.ResponseDeploymentsInfo) *GetExternalDeploymentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get external deployments o k response
func (o *GetExternalDeploymentsOK) SetPayload(payload *models.ResponseDeploymentsInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetExternalDeploymentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetExternalDeploymentsBadRequestCode is the HTTP code returned for type GetExternalDeploymentsBadRequest
const GetExternalDeploymentsBadRequestCode int = 400

/*
GetExternalDeploymentsBadRequest Error

swagger:response getExternalDeploymentsBadRequest
*/
type GetExternalDeploymentsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewGetExternalDeploymentsBadRequest creates GetExternalDeploymentsBadRequest with default headers values
func NewGetExternalDeploymentsBadRequest() *GetExternalDeploymentsBadRequest {

	return &GetExternalDeploymentsBadRequest{}
}

// WithPayload adds the payload to the get external deployments bad request response
func (o *GetExternalDeploymentsBadRequest) WithPayload(payload *models.ResponseError) *GetExternalDeploymentsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get external deployments bad request response
func (o *GetExternalDeploymentsBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetExternalDeploymentsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
