// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteSecretsIDHandlerFunc turns a function with the right signature into a delete secrets ID handler
type DeleteSecretsIDHandlerFunc func(DeleteSecretsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteSecretsIDHandlerFunc) Handle(params DeleteSecretsIDParams) middleware.Responder {
	return fn(params)
}

// DeleteSecretsIDHandler interface for that can handle valid delete secrets ID params
type DeleteSecretsIDHandler interface {
	Handle(DeleteSecretsIDParams) middleware.Responder
}

// NewDeleteSecretsID creates a new http.Handler for the delete secrets ID operation
func NewDeleteSecretsID(ctx *middleware.Context, handler DeleteSecretsIDHandler) *DeleteSecretsID {
	return &DeleteSecretsID{Context: ctx, Handler: handler}
}

/*
	DeleteSecretsID swagger:route DELETE /secrets/{id} secret deleteSecretsId

Delete secret
*/
type DeleteSecretsID struct {
	Context *middleware.Context
	Handler DeleteSecretsIDHandler
}

func (o *DeleteSecretsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteSecretsIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
