// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchSecretsIDHandlerFunc turns a function with the right signature into a patch secrets ID handler
type PatchSecretsIDHandlerFunc func(PatchSecretsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchSecretsIDHandlerFunc) Handle(params PatchSecretsIDParams) middleware.Responder {
	return fn(params)
}

// PatchSecretsIDHandler interface for that can handle valid patch secrets ID params
type PatchSecretsIDHandler interface {
	Handle(PatchSecretsIDParams) middleware.Responder
}

// NewPatchSecretsID creates a new http.Handler for the patch secrets ID operation
func NewPatchSecretsID(ctx *middleware.Context, handler PatchSecretsIDHandler) *PatchSecretsID {
	return &PatchSecretsID{Context: ctx, Handler: handler}
}

/*
	PatchSecretsID swagger:route PATCH /secrets/{id} secret patchSecretsId

Change secret
*/
type PatchSecretsID struct {
	Context *middleware.Context
	Handler PatchSecretsIDHandler
}

func (o *PatchSecretsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchSecretsIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
