// Code generated by go-swagger; DO NOT EDIT.

package secret

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostSecretsHandlerFunc turns a function with the right signature into a post secrets handler
type PostSecretsHandlerFunc func(PostSecretsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostSecretsHandlerFunc) Handle(params PostSecretsParams) middleware.Responder {
	return fn(params)
}

// PostSecretsHandler interface for that can handle valid post secrets params
type PostSecretsHandler interface {
	Handle(PostSecretsParams) middleware.Responder
}

// NewPostSecrets creates a new http.Handler for the post secrets operation
func NewPostSecrets(ctx *middleware.Context, handler PostSecretsHandler) *PostSecrets {
	return &PostSecrets{Context: ctx, Handler: handler}
}

/*
	PostSecrets swagger:route POST /secrets secret postSecrets

Create new secret
*/
type PostSecrets struct {
	Context *middleware.Context
	Handler PostSecretsHandler
}

func (o *PostSecrets) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostSecretsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
