// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteProjectsIDHandlerFunc turns a function with the right signature into a delete projects ID handler
type DeleteProjectsIDHandlerFunc func(DeleteProjectsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteProjectsIDHandlerFunc) Handle(params DeleteProjectsIDParams) middleware.Responder {
	return fn(params)
}

// DeleteProjectsIDHandler interface for that can handle valid delete projects ID params
type DeleteProjectsIDHandler interface {
	Handle(DeleteProjectsIDParams) middleware.Responder
}

// NewDeleteProjectsID creates a new http.Handler for the delete projects ID operation
func NewDeleteProjectsID(ctx *middleware.Context, handler DeleteProjectsIDHandler) *DeleteProjectsID {
	return &DeleteProjectsID{Context: ctx, Handler: handler}
}

/*
	DeleteProjectsID swagger:route DELETE /projects/{id} project deleteProjectsId

Delete project
*/
type DeleteProjectsID struct {
	Context *middleware.Context
	Handler DeleteProjectsIDHandler
}

func (o *DeleteProjectsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteProjectsIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
