// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetProjectsHandlerFunc turns a function with the right signature into a get projects handler
type GetProjectsHandlerFunc func(GetProjectsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProjectsHandlerFunc) Handle(params GetProjectsParams) middleware.Responder {
	return fn(params)
}

// GetProjectsHandler interface for that can handle valid get projects params
type GetProjectsHandler interface {
	Handle(GetProjectsParams) middleware.Responder
}

// NewGetProjects creates a new http.Handler for the get projects operation
func NewGetProjects(ctx *middleware.Context, handler GetProjectsHandler) *GetProjects {
	return &GetProjects{Context: ctx, Handler: handler}
}

/*
	GetProjects swagger:route GET /projects project getProjects

Get projects list
*/
type GetProjects struct {
	Context *middleware.Context
	Handler GetProjectsHandler
}

func (o *GetProjects) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetProjectsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
