---
- name: "Edit patroni.yml | enable noloadbalance, nosync, nofailover"
  replace:
    path: /etc/patroni/patroni.yml
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: 'noloadbalance: false', replace: 'noloadbalance: true' }
    - { regexp: 'nosync: false', replace: 'nosync: true' }
    - { regexp: 'nofailover: false', replace: 'nofailover: true' }
  loop_control:
    label: '{{ item.replace }}'

- name: Reload patroni service
  systemd:
    daemon_reload: true
    name: patroni
    enabled: true
    state: reloaded

- name: Make sure replica endpoint is unavailable
  uri:
    url: http://{{ inventory_hostname }}:{{ patroni_restapi_port }}/replica
    status_code: 503
  register: patroni_replica_result
  until: patroni_replica_result.status == 503
  retries: 30
  delay: 2

- name: Wait for active transactions to complete
  become: true
  become_user: postgres
  command: >-
    psql -tAXc "select
    count(*) from pg_stat_activity
    where pid <> pg_backend_pid()
    and backend_type = 'client backend'
    and state = 'active'"
  register: pg_active_count
  until: pg_active_count.stdout|int == 0
  retries: 300
  delay: 2
  changed_when: false
...
