// Code generated by go-swagger; DO NOT EDIT.

package setting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"postgesql-cluster-console/models"
)

// GetSettingsOKCode is the HTTP code returned for type GetSettingsOK
const GetSettingsOKCode int = 200

/*
GetSettingsOK OK

swagger:response getSettingsOK
*/
type GetSettingsOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseSettings `json:"body,omitempty"`
}

// NewGetSettingsOK creates GetSettingsOK with default headers values
func NewGetSettingsOK() *GetSettingsOK {

	return &GetSettingsOK{}
}

// WithPayload adds the payload to the get settings o k response
func (o *GetSettingsOK) WithPayload(payload *models.ResponseSettings) *GetSettingsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get settings o k response
func (o *GetSettingsOK) SetPayload(payload *models.ResponseSettings) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSettingsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSettingsBadRequestCode is the HTTP code returned for type GetSettingsBadRequest
const GetSettingsBadRequestCode int = 400

/*
GetSettingsBadRequest Error

swagger:response getSettingsBadRequest
*/
type GetSettingsBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewGetSettingsBadRequest creates GetSettingsBadRequest with default headers values
func NewGetSettingsBadRequest() *GetSettingsBadRequest {

	return &GetSettingsBadRequest{}
}

// WithPayload adds the payload to the get settings bad request response
func (o *GetSettingsBadRequest) WithPayload(payload *models.ResponseError) *GetSettingsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get settings bad request response
func (o *GetSettingsBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSettingsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
