// Code generated by go-swagger; DO NOT EDIT.

package setting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchSettingsNameHandlerFunc turns a function with the right signature into a patch settings name handler
type PatchSettingsNameHandlerFunc func(PatchSettingsNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchSettingsNameHandlerFunc) Handle(params PatchSettingsNameParams) middleware.Responder {
	return fn(params)
}

// PatchSettingsNameHandler interface for that can handle valid patch settings name params
type PatchSettingsNameHandler interface {
	Handle(PatchSettingsNameParams) middleware.Responder
}

// NewPatchSettingsName creates a new http.Handler for the patch settings name operation
func NewPatchSettingsName(ctx *middleware.Context, handler PatchSettingsNameHandler) *PatchSettingsName {
	return &PatchSettingsName{Context: ctx, Handler: handler}
}

/*
	PatchSettingsName swagger:route PATCH /settings/{name} setting patchSettingsName

Changed setting
*/
type PatchSettingsName struct {
	Context *middleware.Context
	Handler PatchSettingsNameHandler
}

func (o *PatchSettingsName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPatchSettingsNameParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
