// Code generated by go-swagger; DO NOT EDIT.

package setting

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostSettingsHandlerFunc turns a function with the right signature into a post settings handler
type PostSettingsHandlerFunc func(PostSettingsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostSettingsHandlerFunc) Handle(params PostSettingsParams) middleware.Responder {
	return fn(params)
}

// PostSettingsHandler interface for that can handle valid post settings params
type PostSettingsHandler interface {
	Handle(PostSettingsParams) middleware.Responder
}

// NewPostSettings creates a new http.Handler for the post settings operation
func NewPostSettings(ctx *middleware.Context, handler PostSettingsHandler) *PostSettings {
	return &PostSettings{Context: ctx, Handler: handler}
}

/*
	PostSettings swagger:route POST /settings setting postSettings

Create new setting
*/
type PostSettings struct {
	Context *middleware.Context
	Handler PostSettingsHandler
}

func (o *PostSettings) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostSettingsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
