import { CLUSTER_TABLE_COLUMN_NAMES } from '@widgets/clusters-table/model/constants.ts';

export interface ClustersTableValues {
  [CLUSTER_TABLE_COLUMN_NAMES.NAME]: string;
  [CLUSTER_TABLE_COLUMN_NAMES.STATUS]: Element;
  [CLUSTER_TABLE_COLUMN_NAMES.CREATION_TIME]: string;
  [CLUSTER_TABLE_COLUMN_NAMES.ENVIRONMENT]: string;
  [CLUSTER_TABLE_COLUMN_NAMES.SERVERS]: number;
  [CLUSTER_TABLE_COLUMN_NAMES.POSTGRES_VERSION]: number;
  [CLUSTER_TABLE_COLUMN_NAMES.LOCATION]: string;
}
