---

dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: 10.172.0.17
    hostname: dcs-node01
    image: "${IMAGE_NAMESPACE:-geerlingguy}/docker-${IMAGE_DISTRO:-centos8}-ansible:${IMAGE_TAG:-latest}"
    # docker_networks:  # TODO github.com/ansible-community/molecule/pull/2696
      # - name: test_docker_network
        # ipam_config:
          # - subnet: 10.172.0.0/24
            # gateway: 10.172.0.1
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.17
    exposed_ports:
      - 2379/tcp  # if dcs_type: "etcd"
      - 2380/tcp  # if dcs_type: "etcd"
      - 8300/tcp  # if dcs_type: "consul"
      - 8301/tcp  # if dcs_type: "consul"
      - 8302/tcp  # if dcs_type: "consul"
      - 8500/tcp  # if dcs_type: "consul"
      - 8600/tcp  # if dcs_type: "consul"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - etcd_cluster  # if dcs_type: "etcd"
      - consul_instances  # if dcs_type: "consul"

  - name: 10.172.0.18
    hostname: dcs-node02
    image: "${IMAGE_NAMESPACE:-geerlingguy}/docker-${IMAGE_DISTRO:-centos8}-ansible:${IMAGE_TAG:-latest}"
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.18
    exposed_ports:
      - 2379/tcp
      - 2380/tcp
      - 8300/tcp
      - 8301/tcp
      - 8302/tcp
      - 8500/tcp
      - 8600/tcp
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - etcd_cluster
      - consul_instances

  - name: 10.172.0.19
    hostname: dcs-node03
    image: "${IMAGE_NAMESPACE:-geerlingguy}/docker-${IMAGE_DISTRO:-centos8}-ansible:${IMAGE_TAG:-latest}"
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.19
    exposed_ports:
      - 2379/tcp
      - 2380/tcp
      - 8300/tcp
      - 8301/tcp
      - 8302/tcp
      - 8500/tcp
      - 8600/tcp
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - etcd_cluster
      - consul_instances

  - name: 10.172.0.20
    hostname: pgnode01
    image: "${IMAGE_NAMESPACE:-geerlingguy}/docker-${IMAGE_DISTRO:-centos8}-ansible:${IMAGE_TAG:-latest}"
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.20
    exposed_ports:
      - 8008/tcp
      - 5432/tcp
      - 6432/tcp
      - 8300/tcp  # if dcs_type: "consul"
      - 8301/tcp  # if dcs_type: "consul"
      - 8302/tcp  # if dcs_type: "consul"
      - 8500/tcp  # if dcs_type: "consul"
      - 8600/tcp  # if dcs_type: "consul"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - master
      - postgres_cluster
      - balancers
      - consul_instances

  - name: 10.172.0.21
    hostname: pgnode02
    image: "${IMAGE_NAMESPACE:-geerlingguy}/docker-${IMAGE_DISTRO:-centos8}-ansible:${IMAGE_TAG:-latest}"
    networks:
      - name: test_docker_network
        ipv4_address: 10.172.0.21
    exposed_ports:
      - 8008/tcp
      - 5432/tcp
      - 6432/tcp
      - 8300/tcp
      - 8301/tcp
      - 8302/tcp
      - 8500/tcp
      - 8600/tcp
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - replica
      - postgres_cluster
      - balancers
      - consul_instances

provisioner:
  name: ansible
  config_options:
    defaults:
      display_skipped_hosts: false
      remote_tmp: "~/.ansible/tmp"
      allow_world_readable_tmpfiles: false
      timeout: 60
  inventory:
    links:
      group_vars: ../../group_vars/
    host_vars:
      10.172.0.17:  # dcs-node01
        consul_node_role: server  # if dcs_type: "consul"
        consul_bootstrap_expect: true  # if dcs_type: "consul"
      10.172.0.18:  # dcs-node02
        consul_node_role: server
        consul_bootstrap_expect: true
      10.172.0.19:  # dcs-node03
        consul_node_role: server
        consul_bootstrap_expect: true
      10.172.0.20:  # pgnode01
        consul_node_role: client
      10.172.0.21:  # pgnode02
        consul_node_role: client
  playbooks:
    prepare: prepare.yml

scenario:
  create_sequence:
    - prepare
    - create
  converge_sequence:
    - prepare
    - create
    - converge
  destroy_sequence:
    - cleanup
    - destroy
  test_sequence:
    - cleanup
    - destroy
    - syntax
    - prepare
    - create
    - converge
#    - idempotence  # >> role:patroni,task:"data directory check result"
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  enabled: false  # TODO

...
