// Code generated by go-swagger; DO NOT EDIT.

package environment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteEnvironmentsIDHandlerFunc turns a function with the right signature into a delete environments ID handler
type DeleteEnvironmentsIDHandlerFunc func(DeleteEnvironmentsIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteEnvironmentsIDHandlerFunc) Handle(params DeleteEnvironmentsIDParams) middleware.Responder {
	return fn(params)
}

// DeleteEnvironmentsIDHandler interface for that can handle valid delete environments ID params
type DeleteEnvironmentsIDHandler interface {
	Handle(DeleteEnvironmentsIDParams) middleware.Responder
}

// NewDeleteEnvironmentsID creates a new http.Handler for the delete environments ID operation
func NewDeleteEnvironmentsID(ctx *middleware.Context, handler DeleteEnvironmentsIDHandler) *DeleteEnvironmentsID {
	return &DeleteEnvironmentsID{Context: ctx, Handler: handler}
}

/*
	DeleteEnvironmentsID swagger:route DELETE /environments/{id} environment deleteEnvironmentsId

Delete environment
*/
type DeleteEnvironmentsID struct {
	Context *middleware.Context
	Handler DeleteEnvironmentsIDHandler
}

func (o *DeleteEnvironmentsID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteEnvironmentsIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
