// Code generated by go-swagger; DO NOT EDIT.

package environment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetEnvironmentsHandlerFunc turns a function with the right signature into a get environments handler
type GetEnvironmentsHandlerFunc func(GetEnvironmentsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetEnvironmentsHandlerFunc) Handle(params GetEnvironmentsParams) middleware.Responder {
	return fn(params)
}

// GetEnvironmentsHandler interface for that can handle valid get environments params
type GetEnvironmentsHandler interface {
	Handle(GetEnvironmentsParams) middleware.Responder
}

// NewGetEnvironments creates a new http.Handler for the get environments operation
func NewGetEnvironments(ctx *middleware.Context, handler GetEnvironmentsHandler) *GetEnvironments {
	return &GetEnvironments{Context: ctx, Handler: handler}
}

/*
	GetEnvironments swagger:route GET /environments environment getEnvironments

Get environemtns list
*/
type GetEnvironments struct {
	Context *middleware.Context
	Handler GetEnvironmentsHandler
}

func (o *GetEnvironments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetEnvironmentsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
