// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteClustersIDHandlerFunc turns a function with the right signature into a delete clusters ID handler
type DeleteClustersIDHandlerFunc func(DeleteClustersIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteClustersIDHandlerFunc) Handle(params DeleteClustersIDParams) middleware.Responder {
	return fn(params)
}

// DeleteClustersIDHandler interface for that can handle valid delete clusters ID params
type DeleteClustersIDHandler interface {
	Handle(DeleteClustersIDParams) middleware.Responder
}

// NewDeleteClustersID creates a new http.Handler for the delete clusters ID operation
func NewDeleteClustersID(ctx *middleware.Context, handler DeleteClustersIDHandler) *DeleteClustersID {
	return &DeleteClustersID{Context: ctx, Handler: handler}
}

/*
	DeleteClustersID swagger:route DELETE /clusters/{id} cluster deleteClustersId

Delete cluster
*/
type DeleteClustersID struct {
	Context *middleware.Context
	Handler DeleteClustersIDHandler
}

func (o *DeleteClustersID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteClustersIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
