// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"postgesql-cluster-console/models"
)

// GetClustersOKCode is the HTTP code returned for type GetClustersOK
const GetClustersOKCode int = 200

/*
GetClustersOK OK

swagger:response getClustersOK
*/
type GetClustersOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseClustersInfo `json:"body,omitempty"`
}

// NewGetClustersOK creates GetClustersOK with default headers values
func NewGetClustersOK() *GetClustersOK {

	return &GetClustersOK{}
}

// WithPayload adds the payload to the get clusters o k response
func (o *GetClustersOK) WithPayload(payload *models.ResponseClustersInfo) *GetClustersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters o k response
func (o *GetClustersOK) SetPayload(payload *models.ResponseClustersInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClustersBadRequestCode is the HTTP code returned for type GetClustersBadRequest
const GetClustersBadRequestCode int = 400

/*
GetClustersBadRequest Error

swagger:response getClustersBadRequest
*/
type GetClustersBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewGetClustersBadRequest creates GetClustersBadRequest with default headers values
func NewGetClustersBadRequest() *GetClustersBadRequest {

	return &GetClustersBadRequest{}
}

// WithPayload adds the payload to the get clusters bad request response
func (o *GetClustersBadRequest) WithPayload(payload *models.ResponseError) *GetClustersBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters bad request response
func (o *GetClustersBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
