// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetClustersIDHandlerFunc turns a function with the right signature into a get clusters ID handler
type GetClustersIDHandlerFunc func(GetClustersIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClustersIDHandlerFunc) Handle(params GetClustersIDParams) middleware.Responder {
	return fn(params)
}

// GetClustersIDHandler interface for that can handle valid get clusters ID params
type GetClustersIDHandler interface {
	Handle(GetClustersIDParams) middleware.Responder
}

// NewGetClustersID creates a new http.Handler for the get clusters ID operation
func NewGetClustersID(ctx *middleware.Context, handler GetClustersIDHandler) *GetClustersID {
	return &GetClustersID{Context: ctx, Handler: handler}
}

/*
	GetClustersID swagger:route GET /clusters/{id} cluster getClustersId

Get cluster info
*/
type GetClustersID struct {
	Context *middleware.Context
	Handler GetClustersIDHandler
}

func (o *GetClustersID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetClustersIDParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
