// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"postgesql-cluster-console/models"
)

// GetClustersDefaultNameOKCode is the HTTP code returned for type GetClustersDefaultNameOK
const GetClustersDefaultNameOKCode int = 200

/*
GetClustersDefaultNameOK OK

swagger:response getClustersDefaultNameOK
*/
type GetClustersDefaultNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseClusterDefaultName `json:"body,omitempty"`
}

// NewGetClustersDefaultNameOK creates GetClustersDefaultNameOK with default headers values
func NewGetClustersDefaultNameOK() *GetClustersDefaultNameOK {

	return &GetClustersDefaultNameOK{}
}

// WithPayload adds the payload to the get clusters default name o k response
func (o *GetClustersDefaultNameOK) WithPayload(payload *models.ResponseClusterDefaultName) *GetClustersDefaultNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters default name o k response
func (o *GetClustersDefaultNameOK) SetPayload(payload *models.ResponseClusterDefaultName) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersDefaultNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetClustersDefaultNameBadRequestCode is the HTTP code returned for type GetClustersDefaultNameBadRequest
const GetClustersDefaultNameBadRequestCode int = 400

/*
GetClustersDefaultNameBadRequest Error

swagger:response getClustersDefaultNameBadRequest
*/
type GetClustersDefaultNameBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewGetClustersDefaultNameBadRequest creates GetClustersDefaultNameBadRequest with default headers values
func NewGetClustersDefaultNameBadRequest() *GetClustersDefaultNameBadRequest {

	return &GetClustersDefaultNameBadRequest{}
}

// WithPayload adds the payload to the get clusters default name bad request response
func (o *GetClustersDefaultNameBadRequest) WithPayload(payload *models.ResponseError) *GetClustersDefaultNameBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get clusters default name bad request response
func (o *GetClustersDefaultNameBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetClustersDefaultNameBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
