// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetClustersHandlerFunc turns a function with the right signature into a get clusters handler
type GetClustersHandlerFunc func(GetClustersParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetClustersHandlerFunc) Handle(params GetClustersParams) middleware.Responder {
	return fn(params)
}

// GetClustersHandler interface for that can handle valid get clusters params
type GetClustersHandler interface {
	Handle(GetClustersParams) middleware.Responder
}

// NewGetClusters creates a new http.Handler for the get clusters operation
func NewGetClusters(ctx *middleware.Context, handler GetClustersHandler) *GetClusters {
	return &GetClusters{Context: ctx, Handler: handler}
}

/*
	GetClusters swagger:route GET /clusters cluster getClusters

Get info about clusters
*/
type GetClusters struct {
	Context *middleware.Context
	Handler GetClustersHandler
}

func (o *GetClusters) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetClustersParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
