// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostClustersIDRefreshHandlerFunc turns a function with the right signature into a post clusters ID refresh handler
type PostClustersIDRefreshHandlerFunc func(PostClustersIDRefreshParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostClustersIDRefreshHandlerFunc) Handle(params PostClustersIDRefreshParams) middleware.Responder {
	return fn(params)
}

// PostClustersIDRefreshHandler interface for that can handle valid post clusters ID refresh params
type PostClustersIDRefreshHandler interface {
	Handle(PostClustersIDRefreshParams) middleware.Responder
}

// NewPostClustersIDRefresh creates a new http.Handler for the post clusters ID refresh operation
func NewPostClustersIDRefresh(ctx *middleware.Context, handler PostClustersIDRefreshHandler) *PostClustersIDRefresh {
	return &PostClustersIDRefresh{Context: ctx, Handler: handler}
}

/*
	PostClustersIDRefresh swagger:route POST /clusters/{id}/refresh cluster postClustersIdRefresh

Refresh cluster info
*/
type PostClustersIDRefresh struct {
	Context *middleware.Context
	Handler PostClustersIDRefreshHandler
}

func (o *PostClustersIDRefresh) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostClustersIDRefreshParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
