// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostClustersIDStopHandlerFunc turns a function with the right signature into a post clusters ID stop handler
type PostClustersIDStopHandlerFunc func(PostClustersIDStopParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostClustersIDStopHandlerFunc) Handle(params PostClustersIDStopParams) middleware.Responder {
	return fn(params)
}

// PostClustersIDStopHandler interface for that can handle valid post clusters ID stop params
type PostClustersIDStopHandler interface {
	Handle(PostClustersIDStopParams) middleware.Responder
}

// NewPostClustersIDStop creates a new http.Handler for the post clusters ID stop operation
func NewPostClustersIDStop(ctx *middleware.Context, handler PostClustersIDStopHandler) *PostClustersIDStop {
	return &PostClustersIDStop{Context: ctx, Handler: handler}
}

/*
	PostClustersIDStop swagger:route POST /clusters/{id}/stop cluster postClustersIdStop

Stop cluster
*/
type PostClustersIDStop struct {
	Context *middleware.Context
	Handler PostClustersIDStopHandler
}

func (o *PostClustersIDStop) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostClustersIDStopParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
