// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostClustersIDReinitHandlerFunc turns a function with the right signature into a post clusters ID reinit handler
type PostClustersIDReinitHandlerFunc func(PostClustersIDReinitParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostClustersIDReinitHandlerFunc) Handle(params PostClustersIDReinitParams) middleware.Responder {
	return fn(params)
}

// PostClustersIDReinitHandler interface for that can handle valid post clusters ID reinit params
type PostClustersIDReinitHandler interface {
	Handle(PostClustersIDReinitParams) middleware.Responder
}

// NewPostClustersIDReinit creates a new http.Handler for the post clusters ID reinit operation
func NewPostClustersIDReinit(ctx *middleware.Context, handler PostClustersIDReinitHandler) *PostClustersIDReinit {
	return &PostClustersIDReinit{Context: ctx, Handler: handler}
}

/*
	PostClustersIDReinit swagger:route POST /clusters/{id}/reinit cluster postClustersIdReinit

Reinit cluster
*/
type PostClustersIDReinit struct {
	Context *middleware.Context
	Handler PostClustersIDReinitHandler
}

func (o *PostClustersIDReinit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostClustersIDReinitParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
