// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostClustersIDStartHandlerFunc turns a function with the right signature into a post clusters ID start handler
type PostClustersIDStartHandlerFunc func(PostClustersIDStartParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostClustersIDStartHandlerFunc) Handle(params PostClustersIDStartParams) middleware.Responder {
	return fn(params)
}

// PostClustersIDStartHandler interface for that can handle valid post clusters ID start params
type PostClustersIDStartHandler interface {
	Handle(PostClustersIDStartParams) middleware.Responder
}

// NewPostClustersIDStart creates a new http.Handler for the post clusters ID start operation
func NewPostClustersIDStart(ctx *middleware.Context, handler PostClustersIDStartHandler) *PostClustersIDStart {
	return &PostClustersIDStart{Context: ctx, Handler: handler}
}

/*
	PostClustersIDStart swagger:route POST /clusters/{id}/start cluster postClustersIdStart

Start cluster
*/
type PostClustersIDStart struct {
	Context *middleware.Context
	Handler PostClustersIDStartHandler
}

func (o *PostClustersIDStart) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostClustersIDStartParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
