// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClusterInfoAdditionalSettings Additional settings for cluster
//
// swagger:model ClusterInfo.AdditionalSettings
type ClusterInfoAdditionalSettings struct {

	// connection info
	ConnectionInfo interface{} `json:"connection_info,omitempty"`
}

// Validate validates this cluster info additional settings
func (m *ClusterInfoAdditionalSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cluster info additional settings based on context it is used
func (m *ClusterInfoAdditionalSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterInfoAdditionalSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterInfoAdditionalSettings) UnmarshalBinary(b []byte) error {
	var res ClusterInfoAdditionalSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
