// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeploymentInstanceType deployment instance type
//
// swagger:model Deployment.InstanceType
type DeploymentInstanceType struct {

	// code
	// Example: m5.2xlarge
	Code string `json:"code,omitempty"`

	// cpu
	// Example: 8
	CPU int64 `json:"cpu,omitempty"`

	// Price currency
	// Example: $
	Currency string `json:"currency,omitempty"`

	// Price for 1 instance by hour
	// Example: 0.01
	PriceHourly float64 `json:"price_hourly,omitempty"`

	// Price for 1 instance by month
	// Example: 1.2
	PriceMonthly float64 `json:"price_monthly,omitempty"`

	// ram
	// Example: 256
	RAM int64 `json:"ram,omitempty"`
}

// Validate validates this deployment instance type
func (m *DeploymentInstanceType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this deployment instance type based on context it is used
func (m *DeploymentInstanceType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeploymentInstanceType) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeploymentInstanceType) UnmarshalBinary(b []byte) error {
	var res DeploymentInstanceType
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
