// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetaPagination Pagination info for list requests
//
// swagger:model Meta.Pagination
type MetaPagination struct {

	// count
	Count *int64 `json:"count,omitempty"`

	// limit
	Limit *int64 `json:"limit,omitempty"`

	// offset
	Offset *int64 `json:"offset,omitempty"`
}

// Validate validates this meta pagination
func (m *MetaPagination) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this meta pagination based on context it is used
func (m *MetaPagination) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetaPagination) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetaPagination) UnmarshalBinary(b []byte) error {
	var res MetaPagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
