// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestSecretPatch request secret patch
//
// swagger:model Request.SecretPatch
type RequestSecretPatch struct {

	// name
	// Example: aws key
	Name *string `json:"name,omitempty"`

	// type
	// Example: aws
	Type *string `json:"type,omitempty"`

	// Secret value in base64
	// Example: c2VjcmV0
	Value *string `json:"value,omitempty"`
}

// Validate validates this request secret patch
func (m *RequestSecretPatch) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request secret patch based on context it is used
func (m *RequestSecretPatch) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestSecretPatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestSecretPatch) UnmarshalBinary(b []byte) error {
	var res RequestSecretPatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
