// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestSecretValueAws request secret value aws
//
// swagger:model Request.SecretValue.Aws
type RequestSecretValueAws struct {

	// a w s a c c e s s k e y ID
	AWSACCESSKEYID string `json:"AWS_ACCESS_KEY_ID,omitempty"`

	// a w s s e c r e t a c c e s s k e y
	AWSSECRETACCESSKEY string `json:"AWS_SECRET_ACCESS_KEY,omitempty"`
}

// Validate validates this request secret value aws
func (m *RequestSecretValueAws) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request secret value aws based on context it is used
func (m *RequestSecretValueAws) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestSecretValueAws) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestSecretValueAws) UnmarshalBinary(b []byte) error {
	var res RequestSecretValueAws
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
