// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestSecretValueDigitalOcean request secret value digital ocean
//
// swagger:model Request.SecretValue.DigitalOcean
type RequestSecretValueDigitalOcean struct {

	// d o API t o k e n
	DOAPITOKEN string `json:"DO_API_TOKEN,omitempty"`
}

// Validate validates this request secret value digital ocean
func (m *RequestSecretValueDigitalOcean) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request secret value digital ocean based on context it is used
func (m *RequestSecretValueDigitalOcean) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestSecretValueDigitalOcean) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestSecretValueDigitalOcean) UnmarshalBinary(b []byte) error {
	var res RequestSecretValueDigitalOcean
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
