// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestEnvironment request environment
//
// swagger:model Request.Environment
type RequestEnvironment struct {

	// description
	// Example: environment for production
	Description string `json:"description,omitempty"`

	// name
	// Example: production
	Name string `json:"name,omitempty"`
}

// Validate validates this request environment
func (m *RequestEnvironment) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request environment based on context it is used
func (m *RequestEnvironment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestEnvironment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestEnvironment) UnmarshalBinary(b []byte) error {
	var res RequestEnvironment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
