// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// RequestClusterRemove Remove cluster
//
// swagger:model Request.ClusterRemove
type RequestClusterRemove interface{}
