// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestProjectPatch request project patch
//
// swagger:model Request.ProjectPatch
type RequestProjectPatch struct {

	// description
	Description *string `json:"description,omitempty"`

	// name
	Name *string `json:"name,omitempty"`
}

// Validate validates this request project patch
func (m *RequestProjectPatch) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request project patch based on context it is used
func (m *RequestProjectPatch) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestProjectPatch) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestProjectPatch) UnmarshalBinary(b []byte) error {
	var res RequestProjectPatch
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
