// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestSecretValueAzure request secret value azure
//
// swagger:model Request.SecretValue.Azure
type RequestSecretValueAzure struct {

	// a z u r e c l i e n t ID
	AZURECLIENTID string `json:"AZURE_CLIENT_ID,omitempty"`

	// a z u r e s e c r e t
	AZURESECRET string `json:"AZURE_SECRET,omitempty"`

	// a z u r e s u b s c r IP t i o n ID
	AZURESUBSCRIPTIONID string `json:"AZURE_SUBSCRIPTION_ID,omitempty"`

	// a z u r e t e n a n t
	AZURETENANT string `json:"AZURE_TENANT,omitempty"`
}

// Validate validates this request secret value azure
func (m *RequestSecretValueAzure) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request secret value azure based on context it is used
func (m *RequestSecretValueAzure) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestSecretValueAzure) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestSecretValueAzure) UnmarshalBinary(b []byte) error {
	var res RequestSecretValueAzure
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
