// Code generated by go-swagger; DO NOT EDIT.

// Package restapi PG Console
//
//	API for PG Console WEB
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /api/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//	  - plain/text
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
