-- cloud_regions

CREATE TABLE public.cloud_regions (
    cloud_provider text NOT NULL,
    region_group text NOT NULL,
    region_name text NOT NULL,
    region_description text NOT NULL
);

COMMENT ON TABLE public.cloud_regions IS 'Table containing cloud regions information for various cloud providers';
COMMENT ON COLUMN public.cloud_regions.cloud_provider IS 'The name of the cloud provider';
COMMENT ON COLUMN public.cloud_regions.region_group IS 'The geographical group of the cloud region';
COMMENT ON COLUMN public.cloud_regions.region_name IS 'The specific name of the cloud region';
COMMENT ON COLUMN public.cloud_regions.region_description IS 'A description of the cloud region';

--ALTER TABLE public.cloud_regions OWNER TO <user>;

INSERT INTO public.cloud_regions (cloud_provider, region_group, region_name, region_description) VALUES
    ('aws', 'Africa', 'af-south-1', 'Africa (Cape Town)'),
    ('aws', 'Asia Pacific', 'ap-east-1', 'Asia Pacific (Hong Kong)'),
    ('aws', 'Asia Pacific', 'ap-south-1', 'Asia Pacific (Mumbai)'),
    ('aws', 'Asia Pacific', 'ap-south-2', 'Asia Pacific (Hyderabad)'),
    ('aws', 'Asia Pacific', 'ap-southeast-3', 'Asia Pacific (Jakarta)'),
    ('aws', 'Asia Pacific', 'ap-southeast-4', 'Asia Pacific (Melbourne)'),
    ('aws', 'Asia Pacific', 'ap-northeast-1', 'Asia Pacific (Tokyo)'),
    ('aws', 'Asia Pacific', 'ap-northeast-2', 'Asia Pacific (Seoul)'),
    ('aws', 'Asia Pacific', 'ap-northeast-3', 'Asia Pacific (Osaka)'),
    ('aws', 'Asia Pacific', 'ap-southeast-1', 'Asia Pacific (Singapore)'),
    ('aws', 'Asia Pacific', 'ap-southeast-2', 'Asia Pacific (Sydney)'),
    ('aws', 'Europe', 'eu-central-1', 'Europe (Frankfurt)'),
    ('aws', 'Europe', 'eu-west-1', 'Europe (Ireland)'),
    ('aws', 'Europe', 'eu-west-2', 'Europe (London)'),
    ('aws', 'Europe', 'eu-west-3', 'Europe (Paris)'),
    ('aws', 'Europe', 'eu-north-1', 'Europe (Stockholm)'),
    ('aws', 'Europe', 'eu-south-1', 'Europe (Milan)'),
    ('aws', 'Europe', 'eu-south-2', 'Europe (Spain)'),
    ('aws', 'Europe', 'eu-central-2', 'Europe (Zurich)'),
    ('aws', 'Middle East', 'me-south-1', 'Middle East (Bahrain)'),
    ('aws', 'Middle East', 'me-central-1', 'Middle East (UAE)'),
    ('aws', 'North America', 'us-east-1', 'US East (N. Virginia)'),
    ('aws', 'North America', 'us-east-2', 'US East (Ohio)'),
    ('aws', 'North America', 'us-west-1', 'US West (N. California)'),
    ('aws', 'North America', 'us-west-2', 'US West (Oregon)'),
    ('aws', 'North America', 'ca-central-1', 'Canada (Central)'),
    ('aws', 'North America', 'ca-west-1', 'Canada (Calgary)'),
    ('aws', 'South America', 'sa-east-1', 'South America (São Paulo)'),
    ('gcp', 'Africa', 'africa-south1', 'Johannesburg'),
    ('gcp', 'Asia Pacific', 'asia-east1', 'Taiwan'),
    ('gcp', 'Asia Pacific', 'asia-east2', 'Hong Kong'),
    ('gcp', 'Asia Pacific', 'asia-northeast1', 'Tokyo'),
    ('gcp', 'Asia Pacific', 'asia-northeast2', 'Osaka'),
    ('gcp', 'Asia Pacific', 'asia-northeast3', 'Seoul'),
    ('gcp', 'Asia Pacific', 'asia-south1', 'Mumbai'),
    ('gcp', 'Asia Pacific', 'asia-south2', 'Delhi'),
    ('gcp', 'Asia Pacific', 'asia-southeast1', 'Singapore'),
    ('gcp', 'Asia Pacific', 'asia-southeast2', 'Jakarta'),
    ('gcp', 'Australia', 'australia-southeast1', 'Sydney'),
    ('gcp', 'Australia', 'australia-southeast2', 'Melbourne'),
    ('gcp', 'Europe', 'europe-central2', 'Warsaw'),
    ('gcp', 'Europe', 'europe-north1', 'Finland'),
    ('gcp', 'Europe', 'europe-southwest1', 'Madrid'),
    ('gcp', 'Europe', 'europe-west1', 'Belgium'),
    ('gcp', 'Europe', 'europe-west10', 'Berlin'),
    ('gcp', 'Europe', 'europe-west12', 'Turin'),
    ('gcp', 'Europe', 'europe-west2', 'London'),
    ('gcp', 'Europe', 'europe-west3', 'Frankfurt'),
    ('gcp', 'Europe', 'europe-west4', 'Netherlands'),
    ('gcp', 'Europe', 'europe-west6', 'Zurich'),
    ('gcp', 'Europe', 'europe-west8', 'Milan'),
    ('gcp', 'Europe', 'europe-west9', 'Paris'),
    ('gcp', 'Middle East', 'me-central1', 'Doha'),
    ('gcp', 'Middle East', 'me-central2', 'Dammam'),
    ('gcp', 'Middle East', 'me-west1', 'Tel Aviv'),
    ('gcp', 'North America', 'northamerica-northeast1', 'Montréal'),
    ('gcp', 'North America', 'northamerica-northeast2', 'Toronto'),
    ('gcp', 'North America', 'us-central1', 'Iowa'),
    ('gcp', 'North America', 'us-east1', 'South Carolina'),
    ('gcp', 'North America', 'us-east4', 'Northern Virginia'),
    ('gcp', 'North America', 'us-east5', 'Columbus'),
    ('gcp', 'North America', 'us-south1', 'Dallas'),
    ('gcp', 'North America', 'us-west1', 'Oregon'),
    ('gcp', 'North America', 'us-west2', 'Los Angeles'),
    ('gcp', 'North America', 'us-west3', 'Salt Lake City'),
    ('gcp', 'North America', 'us-west4', 'Las Vegas'),
    ('gcp', 'South America', 'southamerica-east1', 'São Paulo'),
    ('gcp', 'South America', 'southamerica-west1', 'Santiago'),
    ('azure', 'Africa', 'southafricanorth', 'South Africa North (Johannesburg)'),
    ('azure', 'Africa', 'southafricawest', 'South Africa West (Cape Town)'),
    ('azure', 'Asia Pacific', 'australiacentral', 'Australia Central (Canberra)'),
    ('azure', 'Asia Pacific', 'australiacentral2', 'Australia Central 2 (Canberra)'),
    ('azure', 'Asia Pacific', 'australiaeast', 'Australia East (New South Wales)'),
    ('azure', 'Asia Pacific', 'australiasoutheast', 'Australia Southeast (Victoria)'),
    ('azure', 'Asia Pacific', 'centralindia', 'Central India (Pune)'),
    ('azure', 'Asia Pacific', 'eastasia', 'East Asia (Hong Kong)'),
    ('azure', 'Asia Pacific', 'japaneast', 'Japan East (Tokyo, Saitama)'),
    ('azure', 'Asia Pacific', 'japanwest', 'Japan West (Osaka)'),
    ('azure', 'Asia Pacific', 'jioindiacentral', 'Jio India Central (Nagpur)'),
    ('azure', 'Asia Pacific', 'jioindiawest', 'Jio India West (Jamnagar)'),
    ('azure', 'Asia Pacific', 'koreacentral', 'Korea Central (Seoul)'),
    ('azure', 'Asia Pacific', 'koreasouth', 'Korea South (Busan)'),
    ('azure', 'Asia Pacific', 'southeastasia', 'Southeast Asia (Singapore)'),
    ('azure', 'Asia Pacific', 'southindia', 'South India (Chennai)'),
    ('azure', 'Asia Pacific', 'westindia', 'West India (Mumbai)'),
    ('azure', 'Europe', 'francecentral', 'France Central (Paris)'),
    ('azure', 'Europe', 'francesouth', 'France South (Marseille)'),
    ('azure', 'Europe', 'germanynorth', 'Germany North (Berlin)'),
    ('azure', 'Europe', 'germanywestcentral', 'Germany West Central (Frankfurt)'),
    ('azure', 'Europe', 'italynorth', 'Italy North (Milan)'),
    ('azure', 'Europe', 'northeurope', 'North Europe (Ireland)'),
    ('azure', 'Europe', 'norwayeast', 'Norway East (Norway)'),
    ('azure', 'Europe', 'norwaywest', 'Norway West (Norway)'),
    ('azure', 'Europe', 'polandcentral', 'Poland Central (Warsaw)'),
    ('azure', 'Europe', 'swedencentral', 'Sweden Central (Gävle)'),
    ('azure', 'Europe', 'switzerlandnorth', 'Switzerland North (Zurich)'),
    ('azure', 'Europe', 'switzerlandwest', 'Switzerland West (Geneva)'),
    ('azure', 'Europe', 'uksouth', 'UK South (London)'),
    ('azure', 'Europe', 'ukwest', 'UK West (Cardiff)'),
    ('azure', 'Europe', 'westeurope', 'West Europe (Netherlands)'),
    ('azure', 'Mexico', 'mexicocentral', 'Mexico Central (Querétaro State)'),
    ('azure', 'Middle East', 'qatarcentral', 'Qatar Central (Doha)'),
    ('azure', 'Middle East', 'uaecentral', 'UAE Central (Abu Dhabi)'),
    ('azure', 'Middle East', 'uaenorth', 'UAE North (Dubai)'),
    ('azure', 'South America', 'brazilsouth', 'Brazil South (Sao Paulo State)'),
    ('azure', 'South America', 'brazilsoutheast', 'Brazil Southeast (Rio)'),
    ('azure', 'North America', 'centralus', 'Central US (Iowa)'),
    ('azure', 'North America', 'eastus', 'East US (Virginia)'),
    ('azure', 'North America', 'eastus2', 'East US 2 (Virginia)'),
    ('azure', 'North America', 'eastusstg', 'East US STG (Virginia)'),
    ('azure', 'North America', 'northcentralus', 'North Central US (Illinois)'),
    ('azure', 'North America', 'southcentralus', 'South Central US (Texas)'),
    ('azure', 'North America', 'westcentralus', 'West Central US (Wyoming)'),
    ('azure', 'North America', 'westus', 'West US (California)'),
    ('azure', 'North America', 'westus2', 'West US 2 (Washington)'),
    ('azure', 'North America', 'westus3', 'West US 3 (Phoenix)'),
    ('azure', 'North America', 'canadaeast', 'Canada East (Quebec)'),
    ('azure', 'North America', 'canadacentral', 'Canada Central (Toronto)'),
    ('azure', 'South America', 'brazilus', 'Brazil US (South America)'),
    ('digitalocean', 'Asia Pacific', 'sgp1', 'Singapore (Datacenter 1)'),
    ('digitalocean', 'Asia Pacific', 'blr1', 'Bangalore (Datacenter 1)'),
    ('digitalocean', 'Australia', 'syd1', 'Sydney (Datacenter 1)'),
    ('digitalocean', 'Europe', 'ams3', 'Amsterdam (Datacenter 3)'),
    ('digitalocean', 'Europe', 'lon1', 'London (Datacenter 1)'),
    ('digitalocean', 'Europe', 'fra1', 'Frankfurt (Datacenter 1)'),
    ('digitalocean', 'North America', 'nyc1', 'New York (Datacenter 1)'),
    ('digitalocean', 'North America', 'nyc3', 'New York (Datacenter 3)'),
    ('digitalocean', 'North America', 'sfo2', 'San Francisco (Datacenter 2)'),
    ('digitalocean', 'North America', 'sfo3', 'San Francisco (Datacenter 3)'),
    ('digitalocean', 'North America', 'tor1', 'Toronto (Datacenter 1)'),
    ('hetzner', 'Europe', 'nbg1', 'Nuremberg'),
    ('hetzner', 'Europe', 'zfsn1', 'Falkenstein'),
    ('hetzner', 'Europe', 'hel1', 'Helsinki'),
    ('hetzner', 'North America', 'hil', 'Hillsboro, OR'),
    ('hetzner', 'North America', 'ash', 'Ashburn, VA');

ALTER TABLE ONLY public.cloud_regions
    ADD CONSTRAINT cloud_regions_pkey PRIMARY KEY (cloud_provider, region_group, region_name);

ALTER TABLE ONLY public.cloud_regions
    ADD CONSTRAINT cloud_regions_cloud_provider_fkey FOREIGN KEY (cloud_provider) REFERENCES public.cloud_providers(provider_name);
