---
- name: update_pgcluster.yml | Update PostgreSQL HA Cluster (based on "Patroni")
  hosts: postgres_cluster
  gather_facts: true
  become: true
  become_method: sudo
  any_errors_fatal: true
  pre_tasks:
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
      tags: always
  tasks:
    - name: "[Prepare] Get Patroni Cluster Leader Node"
      ansible.builtin.uri:
        url: http://{{ inventory_hostname }}:{{ patroni_restapi_port }}/leader
        status_code: 200
      register: patroni_leader_result
      changed_when: false
      failed_when: false
      environment:
        no_proxy: "{{ inventory_hostname }}"
      tags: always

    - name: '[Prepare] Add host to group "primary" (in-memory inventory)'
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: primary
      when: hostvars[item]['patroni_leader_result']['status'] == 200
      loop: "{{ groups['postgres_cluster'] }}"
      changed_when: false
      tags: always

    - name: '[Prepare] Add hosts to group "secondary" (in-memory inventory)'
      ansible.builtin.add_host:
        name: "{{ item }}"
        groups: secondary
      when: hostvars[item]['patroni_leader_result']['status'] != 200
      loop: "{{ groups['postgres_cluster'] }}"
      changed_when: false
      tags: always

    - name: "Print Patroni Cluster info"
      ansible.builtin.debug:
        msg:
          - "Cluster Name: {{ patroni_cluster_name }}"
          - "Cluster Leader: {{ ansible_hostname }}"
      when: inventory_hostname in groups['primary']
      tags: always

- name: "(1/4) PRE-UPDATE: Perform pre-update tasks"
  hosts: "primary:secondary"
  gather_facts: true
  become: true
  become_user: postgres
  any_errors_fatal: true
  pre_tasks:
    - name: Include role variables
      ansible.builtin.include_vars: "roles/update/vars/main.yml"
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
    - name: Include OS-specific variables
      ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"
  tasks:
    - name: Running Pre-Checks
      ansible.builtin.include_role:
        name: update
        tasks_from: pre_checks

    # This task updates the pgBackRest package on the backup server (Dedicated Repository Host).
    # It runs only if the 'pgbackrest' group is defined in the inventory and the update target is set to 'system'.
    - name: Update pgBackRest package (Dedicated Repository Host)
      ansible.builtin.include_role:
        name: update
        tasks_from: pgbackrest_host
      when: groups['pgbackrest'] | default([]) | length > 0 and target | lower == 'system'
  tags:
    - update
    - pre-checks

- name: "(2/4) UPDATE: Secondary"
  hosts: secondary
  serial: 1 # update replicas one by one
  gather_facts: true
  become: true
  become_method: sudo
  any_errors_fatal: true
  environment: "{{ proxy_env | default({}) }}"
  pre_tasks:
    - name: Include role variables
      ansible.builtin.include_vars: "roles/update/vars/main.yml"
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
    - name: Include OS-specific variables
      ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"
  tasks:
    - name: Stop read-only traffic
      ansible.builtin.include_role:
        name: update
        tasks_from: stop_traffic

    - name: Stop Services
      ansible.builtin.include_role:
        name: update
        tasks_from: stop_services

    - name: Update PostgreSQL
      ansible.builtin.include_role:
        name: update
        tasks_from: postgres
      when: target | lower == 'postgres' or target | lower == 'system'

    - name: Update Patroni
      ansible.builtin.include_role:
        name: update
        tasks_from: patroni
      when: target | lower == 'patroni' or target | lower == 'system'

    - name: Update all system packages
      ansible.builtin.include_role:
        name: update
        tasks_from: system
      when: target | lower == 'system'

    - name: Start Services
      ansible.builtin.include_role:
        name: update
        tasks_from: start_services

    - name: Start read-only traffic
      ansible.builtin.include_role:
        name: update
        tasks_from: start_traffic
  tags:
    - update
    - update-secondary

- name: "(3/4) UPDATE: Primary"
  hosts: primary
  gather_facts: true
  become: true
  become_method: sudo
  any_errors_fatal: true
  environment: "{{ proxy_env | default({}) }}"
  pre_tasks:
    - name: Include role variables
      ansible.builtin.include_vars: "roles/update/vars/main.yml"
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
    - name: Include OS-specific variables
      ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"
  tasks:
    - name: "Switchover Patroni leader role"
      ansible.builtin.include_role:
        name: update
        tasks_from: switchover

    - name: Stop read-only traffic
      ansible.builtin.include_role:
        name: update
        tasks_from: stop_traffic

    - name: Stop Services
      ansible.builtin.include_role:
        name: update
        tasks_from: stop_services

    - name: Update PostgreSQL
      ansible.builtin.include_role:
        name: update
        tasks_from: postgres
      when: target | lower == 'postgres' or target | lower == 'system'

    - name: Update Patroni
      ansible.builtin.include_role:
        name: update
        tasks_from: patroni
      when: target | lower == 'patroni' or target | lower == 'system'

    - name: Update all system packages
      ansible.builtin.include_role:
        name: update
        tasks_from: system
      when: target | lower == 'system'

    - name: Start Services
      ansible.builtin.include_role:
        name: update
        tasks_from: start_services

    - name: Start read-only traffic
      ansible.builtin.include_role:
        name: update
        tasks_from: start_traffic
  tags:
    - update
    - update-primary

- name: "(4/4) POST-UPDATE: Update extensions"
  hosts: postgres_cluster
  gather_facts: true
  become: true
  become_user: postgres
  any_errors_fatal: true
  pre_tasks:
    - name: Include role variables
      ansible.builtin.include_vars: "roles/update/vars/main.yml"
    - name: Include main variables
      ansible.builtin.include_vars: "vars/main.yml"
    - name: Include OS-specific variables
      ansible.builtin.include_vars: "vars/{{ ansible_os_family }}.yml"
  tasks:
    - name: Update extensions
      ansible.builtin.include_role:
        name: update
        tasks_from: extensions
      when: update_extensions | bool

    # finish (info)
    - name: Check for any update failure
      run_once: true # noqa run-once
      ansible.builtin.set_fact:
        any_update_failed: "{{ any_update_failed | default(false) or
          hostvars[item].update_postgres_failed | default(false) or
          hostvars[item].update_patroni_failed | default(false) or
          hostvars[item].update_system_failed | default(false) }}"
      loop: "{{ groups['postgres_cluster'] }}"

    - name: Check the Patroni cluster state
      run_once: true # noqa run-once
      become: true
      become_user: postgres
      ansible.builtin.command: patronictl -c /etc/patroni/patroni.yml list
      register: patronictl_result
      changed_when: false
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/bin:/usr/local/bin"

    - name: Check the current PostgreSQL version
      run_once: true # noqa run-once
      ansible.builtin.command: >-
        {{ postgresql_bin_dir }}/psql -p {{ postgresql_port }} -U {{ patroni_superuser_username }} -d postgres -tAXc
        "select current_setting('server_version')"
      register: postgres_version
      changed_when: false

    - name: List the Patroni cluster members
      run_once: true # noqa run-once
      ansible.builtin.debug:
        msg: "{{ patronictl_result.stdout_lines }}"
      when: patronictl_result.stdout_lines is defined

    # if there are no update errors
    - name: Update completed
      run_once: true # noqa run-once
      ansible.builtin.debug:
        msg:
          - "PostgreSQL HA cluster update completed."
          - "Current version: {{ postgres_version.stdout }}"
      when: not any_update_failed

    # if there were errors during the update
    - name: Update completed with error
      run_once: true # noqa run-once
      ansible.builtin.debug:
        msg:
          - "Update of PostgreSQL HA cluster completed with errors. Check the Ansible log."
          - "Current version: {{ postgres_version.stdout }}"
      when: any_update_failed
  tags:
    - update
    - update-extensions
