// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetOperationsHandlerFunc turns a function with the right signature into a get operations handler
type GetOperationsHandlerFunc func(GetOperationsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetOperationsHandlerFunc) Handle(params GetOperationsParams) middleware.Responder {
	return fn(params)
}

// GetOperationsHandler interface for that can handle valid get operations params
type GetOperationsHandler interface {
	Handle(GetOperationsParams) middleware.Responder
}

// NewGetOperations creates a new http.Handler for the get operations operation
func NewGetOperations(ctx *middleware.Context, handler GetOperationsHandler) *GetOperations {
	return &GetOperations{Context: ctx, Handler: handler}
}

/*
	GetOperations swagger:route GET /operations operation getOperations

Get operations list for current project
*/
type GetOperations struct {
	Context *middleware.Context
	Handler GetOperationsHandler
}

func (o *GetOperations) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetOperationsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
