// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetOperationsURL generates an URL for the get operations operation
type GetOperationsURL struct {
	ClusterName *string
	EndDate     strfmt.DateTime
	Environment *string
	Limit       *int64
	Offset      *int64
	ProjectID   int64
	SortBy      *string
	StartDate   strfmt.DateTime
	Status      *string
	Type        *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetOperationsURL) WithBasePath(bp string) *GetOperationsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetOperationsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetOperationsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/operations"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var clusterNameQ string
	if o.ClusterName != nil {
		clusterNameQ = *o.ClusterName
	}
	if clusterNameQ != "" {
		qs.Set("cluster_name", clusterNameQ)
	}

	endDateQ := o.EndDate.String()
	if endDateQ != "" {
		qs.Set("end_date", endDateQ)
	}

	var environmentQ string
	if o.Environment != nil {
		environmentQ = *o.Environment
	}
	if environmentQ != "" {
		qs.Set("environment", environmentQ)
	}

	var limitQ string
	if o.Limit != nil {
		limitQ = swag.FormatInt64(*o.Limit)
	}
	if limitQ != "" {
		qs.Set("limit", limitQ)
	}

	var offsetQ string
	if o.Offset != nil {
		offsetQ = swag.FormatInt64(*o.Offset)
	}
	if offsetQ != "" {
		qs.Set("offset", offsetQ)
	}

	projectIDQ := swag.FormatInt64(o.ProjectID)
	if projectIDQ != "" {
		qs.Set("project_id", projectIDQ)
	}

	var sortByQ string
	if o.SortBy != nil {
		sortByQ = *o.SortBy
	}
	if sortByQ != "" {
		qs.Set("sort_by", sortByQ)
	}

	startDateQ := o.StartDate.String()
	if startDateQ != "" {
		qs.Set("start_date", startDateQ)
	}

	var statusQ string
	if o.Status != nil {
		statusQ = *o.Status
	}
	if statusQ != "" {
		qs.Set("status", statusQ)
	}

	var typeVarQ string
	if o.Type != nil {
		typeVarQ = *o.Type
	}
	if typeVarQ != "" {
		qs.Set("type", typeVarQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetOperationsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetOperationsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetOperationsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetOperationsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetOperationsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetOperationsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
