// Code generated by go-swagger; DO NOT EDIT.

package operation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	"postgesql-cluster-console/models"
)

// GetOperationsIDLogOKCode is the HTTP code returned for type GetOperationsIDLogOK
const GetOperationsIDLogOKCode int = 200

/*
GetOperationsIDLogOK OK

swagger:response getOperationsIdLogOK
*/
type GetOperationsIDLogOK struct {
	/*

	 */
	ContentType string `json:"content-type"`
	/*

	 */
	XLogCompleted bool `json:"x-log-completed"`

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetOperationsIDLogOK creates GetOperationsIDLogOK with default headers values
func NewGetOperationsIDLogOK() *GetOperationsIDLogOK {

	return &GetOperationsIDLogOK{}
}

// WithContentType adds the contentType to the get operations Id log o k response
func (o *GetOperationsIDLogOK) WithContentType(contentType string) *GetOperationsIDLogOK {
	o.ContentType = contentType
	return o
}

// SetContentType sets the contentType to the get operations Id log o k response
func (o *GetOperationsIDLogOK) SetContentType(contentType string) {
	o.ContentType = contentType
}

// WithXLogCompleted adds the xLogCompleted to the get operations Id log o k response
func (o *GetOperationsIDLogOK) WithXLogCompleted(xLogCompleted bool) *GetOperationsIDLogOK {
	o.XLogCompleted = xLogCompleted
	return o
}

// SetXLogCompleted sets the xLogCompleted to the get operations Id log o k response
func (o *GetOperationsIDLogOK) SetXLogCompleted(xLogCompleted bool) {
	o.XLogCompleted = xLogCompleted
}

// WithPayload adds the payload to the get operations Id log o k response
func (o *GetOperationsIDLogOK) WithPayload(payload string) *GetOperationsIDLogOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get operations Id log o k response
func (o *GetOperationsIDLogOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOperationsIDLogOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header content-type

	contentType := o.ContentType
	if contentType != "" {
		rw.Header().Set("content-type", contentType)
	}

	// response header x-log-completed

	xLogCompleted := swag.FormatBool(o.XLogCompleted)
	if xLogCompleted != "" {
		rw.Header().Set("x-log-completed", xLogCompleted)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetOperationsIDLogBadRequestCode is the HTTP code returned for type GetOperationsIDLogBadRequest
const GetOperationsIDLogBadRequestCode int = 400

/*
GetOperationsIDLogBadRequest Error

swagger:response getOperationsIdLogBadRequest
*/
type GetOperationsIDLogBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ResponseError `json:"body,omitempty"`
}

// NewGetOperationsIDLogBadRequest creates GetOperationsIDLogBadRequest with default headers values
func NewGetOperationsIDLogBadRequest() *GetOperationsIDLogBadRequest {

	return &GetOperationsIDLogBadRequest{}
}

// WithPayload adds the payload to the get operations Id log bad request response
func (o *GetOperationsIDLogBadRequest) WithPayload(payload *models.ResponseError) *GetOperationsIDLogBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get operations Id log bad request response
func (o *GetOperationsIDLogBadRequest) SetPayload(payload *models.ResponseError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOperationsIDLogBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
